---
camera_params: {height: 680, width: 1200, fx: 600.0, fy: 600.0, cx: 599.5, cy: 339.5}

depth_scale: 0.001

pose_axis_transform: [
  [1,  0,  0,  0],
  [0, -1,  0,  0],
  [0,  0, -1,  0],
  [0,  0,  0,  1],
]