pose_axis_transform: [
  [1,  0,  0,  0],
  [0, -1,  0,  0],
  [0,  0, -1,  0],
  [0,  0,  0,  1],
]

semantic_class_stuffs: [1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 19, 21]
semantic_class_things: [4, 5, 6, 14, 15, 16, 17, 18, 20]